# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5579258918856302a55cd9f79eb44ee3ca58f318f9a54fbf724d40816dfb601e3b1b219c0b85393daec4699121b04ad3ab36254a998547e49adfd928a3a5d4fb

test:
  secret_key_base: 9d4346300541abbd33a5185c0a60741587e30d62e6546046d711e2bb71346bb5a4c86080bb19ae138ed8bbecd88ca97aeb5ca7badef69bde03e0387027a03aa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
